name: Workflow for node using Snyk 
on: 
  pull_request:
    branches:
      - master
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high
        # If you want to monitor a project after workflow runs:
        # command: monitor
    
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: create issue from file
        uses: peter-evans/create-issue-from-file@v2.1.0
        with:
          token: ${{ secrets.GITHUB }}
          title: An example issue
          content-filepath: /results/results.md
          labels: report

        
      
